version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3310:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@123
      MYSQL_DATABASE: my_stuff
    restart: always


volumes:
  mysql_data:
    external: true
